In [1]:
import torch # torch means pytorch

In [2]:
torch.__version__ # tested on version 1.1.0

'1.1.0'

In [3]:
torch.manual_seed(42) # to get the same result everytime your run the notebook

**create an array**

In [4]:
a=torch.randn(3,5) # random uniform array of size 3x5 (from normal distribution mean=0, std=1)

In [5]:
a

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
        [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898, -0.9890]])

In [6]:
b=torch.randn(5,2)

In [7]:
b

tensor([[ 0.9580,  1.3221],
        [ 0.8172, -0.7658],
        [-0.7506,  1.3525],
        [ 0.6863, -0.3278],
        [ 0.7950,  0.2815]])

**matrix multplication**

In [8]:
ab=a@b # matrix multiplcation operator is @

In [9]:
ab.shape # .shape gives the dimensions of the array/tensor

torch.Size([3, 2])

In [10]:
ab

tensor([[-0.4827,  0.2720],
        [ 2.6343, -2.8764],
        [-1.6055,  1.8645]])

In [11]:
a=torch.randn(3,5)
b=torch.randn(3,5)

In [12]:
a

tensor([[ 0.0562,  0.5227, -0.2384, -0.0499,  0.5263],
        [-0.0085,  0.7291,  0.1331,  0.8640, -1.0157],
        [-0.8887,  0.1498, -0.2089, -0.3870,  0.9912]])

In [13]:
b

tensor([[ 0.4679, -0.2049, -0.7409,  0.3618,  1.9199],
        [-0.2254, -0.3417,  0.3040, -0.6890, -1.1267],
        [-0.2858, -1.0935,  1.1351,  0.7592, -3.5945]])

**element-wise product (fancy name: Hadamard product)**

In [14]:
a*b # do not confuse it with the @ operation - this does element-wise operations

tensor([[ 2.6279e-02, -1.0712e-01,  1.7660e-01, -1.8057e-02,  1.0105e+00],
        [ 1.9155e-03, -2.4912e-01,  4.0477e-02, -5.9529e-01,  1.1444e+00],
        [ 2.5396e-01, -1.6379e-01, -2.3712e-01, -2.9384e-01, -3.5630e+00]])

**another way to create an array/tensor**

In [15]:
t=torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # create tensor from existing data

In [16]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**tensors of different data types**

In [17]:
t.dtype # tells the datatype

torch.int64

In [18]:
t_f=torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float32) # the numbers here are floating point

In [19]:
t_f # see the decimal dots?

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [20]:
t_f.dtype

torch.float32

In [21]:
t_f.requires_grad # by default PyTorch does not store gradients as it requires extra space

False

**concating multiple tensors**

In [22]:
a=torch.randn(2,5)
b=torch.randn(4,5)

In [23]:
a_concat_b=torch.cat([a,b]) # concat along row (by default, argument dim=0)
# require the columns (generally non-concating axes) to be matching

In [24]:
a_concat_b.shape

torch.Size([6, 5])

In [25]:
a_concat_b

tensor([[ 0.0192,  0.1052,  0.9603, -0.5672, -0.5706],
        [ 1.5980,  0.1115, -0.0392,  1.4112, -0.6556],
        [-0.1360,  1.6354,  0.6547,  0.5760,  1.0414],
        [-0.3997, -2.2933,  0.4976, -0.4257, -1.3371],
        [-0.1933,  0.6526, -0.3063, -0.3302, -0.9808],
        [ 0.1947, -1.6535,  0.6814,  1.4611, -0.3098]])

In [26]:
a=torch.randn(3,5)
b=torch.randn(3,7)

In [27]:
a_concat_b=torch.cat([a,b]) # cannot concat as columns dont match

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 5 and 7 in dimension 1 at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/TH/generic/THTensor.cpp:711

In [28]:
a_concat_b=torch.cat([a,b], dim=1) # concat along second dimension (columns)
# dim is 1 here and the first dimension is 0 

In [29]:
a_concat_b.shape

torch.Size([3, 12])

In [30]:
a_concat_b

tensor([[ 0.8576,  2.1174, -1.7118,  0.1651,  1.5819, -1.1753,  0.3581,  0.4788,
          1.3537, -0.1593,  0.4879,  1.1340],
        [ 0.4485,  0.0330,  1.4503, -0.6936,  0.9967, -0.3556,  0.3618,  1.9993,
          0.6630,  0.7047, -0.0045, -0.8293],
        [ 0.6131,  0.7764, -0.3029, -1.2753, -0.4758, -1.0809, -0.7839,  0.5071,
          0.0821,  0.4440, -0.7240, -0.0720]])

**special tensors**

In [31]:
torch.ones(3,5) # matrix of ones 3x5 shape

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [32]:
k=42
k*torch.ones(3,5) # matrix of 3x5 with a constant (42)
# fun fact: my full name has 42 letters in it !!! 

tensor([[42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42.]])

In [33]:
torch.zeros(3,4) # matrix of 3x5 with 0s

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
torch.eye(5) # identity matrix 5x5, will always be squre matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [35]:
t=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**transpose**

In [37]:
t.t() # as simple as that

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

**reshape**

In [38]:
t.view(9,1) # resape t to 9x1 matrix
# can use .reshape method too, but I like this better
# Note: the resultant shape (9x1) should have the same number of the elements as the original, else PyTorch complains

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [39]:
t.view(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
t.view(2,8) # didn't I tell you?

RuntimeError: shape '[2, 8]' is invalid for input of size 9

**inverse**

In [41]:
t_f=torch.tensor([[1,2.0,3.3],[4.1,5,6.2],[7,8.4,9.2]])

In [42]:
t_f

tensor([[1.0000, 2.0000, 3.3000],
        [4.1000, 5.0000, 6.2000],
        [7.0000, 8.4000, 9.2000]])

In [43]:
t_f.inverse()

tensor([[-1.7716,  2.7156, -1.1946],
        [ 1.6550, -4.0501,  2.1358],
        [-0.1632,  1.6317, -0.9324]])

In [44]:
t_f@t_f.inverse() # A*A_inverse = I
# why dont we get exact identity matrix - there are numerical errors when trying to round off recurrent decimals etc resulting in small numbers close to 0 for off-principal elements

tensor([[ 1.0000e+00,  3.1558e-07,  2.0619e-08],
        [ 1.4139e-07,  1.0000e+00, -1.5594e-07],
        [-1.0358e-06,  7.8550e-07,  1.0000e+00]])

**determinant**

In [45]:
t=torch.eye(3)
torch.det(t) # get the determinant
# determinant of identity matrix is 1

tensor(1.)

**broadcasting**

Beautifully explained here - https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html  
If you did not understand, that is one more good reason to attend the discussion!

In [46]:
a=torch.randint(0,10, (3,4))
a

tensor([[9, 9, 5, 9],
        [7, 0, 3, 1],
        [6, 3, 6, 2]])

In [47]:
b=torch.randint(1,5, (1,4))
b

tensor([[2, 1, 1, 1]])

In [48]:
a+b 
# _ : magic?
# Pythonista: no, broadcasting

tensor([[11, 10,  6, 10],
        [ 9,  1,  4,  2],
        [ 8,  4,  7,  3]])

In [49]:
a=torch.randint(0,10, (3,4,5))
a

tensor([[[8, 3, 0, 5, 2],
         [4, 8, 4, 3, 1],
         [2, 0, 3, 4, 2],
         [2, 1, 3, 7, 0]],

        [[8, 7, 3, 7, 7],
         [2, 5, 4, 7, 2],
         [3, 7, 9, 3, 0],
         [9, 2, 2, 6, 2]],

        [[5, 0, 8, 4, 1],
         [3, 5, 3, 0, 4],
         [7, 6, 2, 2, 7],
         [1, 6, 5, 1, 9]]])

In [50]:
b=torch.randint(1,4, (1,1,5))
b

tensor([[[3, 1, 1, 3, 1]]])

In [51]:
a+b # tadaa!!

tensor([[[11,  4,  1,  8,  3],
         [ 7,  9,  5,  6,  2],
         [ 5,  1,  4,  7,  3],
         [ 5,  2,  4, 10,  1]],

        [[11,  8,  4, 10,  8],
         [ 5,  6,  5, 10,  3],
         [ 6,  8, 10,  6,  1],
         [12,  3,  3,  9,  3]],

        [[ 8,  1,  9,  7,  2],
         [ 6,  6,  4,  3,  5],
         [10,  7,  3,  5,  8],
         [ 4,  7,  6,  4, 10]]])

In [52]:
a=torch.randint(0,10, (3,4,5))
a

tensor([[[8, 5, 8, 8, 6],
         [1, 5, 8, 1, 9],
         [1, 1, 0, 2, 9],
         [1, 6, 0, 9, 6]],

        [[5, 3, 0, 8, 5],
         [3, 4, 9, 8, 3],
         [4, 2, 4, 1, 3],
         [2, 9, 8, 6, 3]],

        [[9, 4, 7, 1, 6],
         [4, 7, 8, 0, 1],
         [4, 2, 7, 1, 0],
         [4, 5, 9, 7, 1]]])

In [53]:
b=torch.randint(1,4, (1,4,1))
b

tensor([[[2],
         [1],
         [2],
         [3]]])

In [54]:
a+b # you gotta love broadcasting

tensor([[[10,  7, 10, 10,  8],
         [ 2,  6,  9,  2, 10],
         [ 3,  3,  2,  4, 11],
         [ 4,  9,  3, 12,  9]],

        [[ 7,  5,  2, 10,  7],
         [ 4,  5, 10,  9,  4],
         [ 6,  4,  6,  3,  5],
         [ 5, 12, 11,  9,  6]],

        [[11,  6,  9,  3,  8],
         [ 5,  8,  9,  1,  2],
         [ 6,  4,  9,  3,  2],
         [ 7,  8, 12, 10,  4]]])

In [55]:
a*b # yes, broadcasting is awesome!

tensor([[[16, 10, 16, 16, 12],
         [ 1,  5,  8,  1,  9],
         [ 2,  2,  0,  4, 18],
         [ 3, 18,  0, 27, 18]],

        [[10,  6,  0, 16, 10],
         [ 3,  4,  9,  8,  3],
         [ 8,  4,  8,  2,  6],
         [ 6, 27, 24, 18,  9]],

        [[18,  8, 14,  2, 12],
         [ 4,  7,  8,  0,  1],
         [ 8,  4, 14,  2,  0],
         [12, 15, 27, 21,  3]]])

**pytorch to numpy and vice-versa**

In [56]:
t=torch.randint(1,10, (3,4))
t

tensor([[5, 1, 7, 2],
        [8, 2, 6, 1],
        [1, 2, 3, 9]])

In [57]:
type(t) # is a Pytorch Tensor

torch.Tensor

In [58]:
t_np=t.numpy() # returns a numpy array with the same data

In [59]:
type(t_np)

numpy.ndarray

In [60]:
import numpy as np

In [61]:
np_arr=np.random.randint(1,10, (3,4))

In [62]:
tsr=torch.from_numpy(np_arr) # numpy array to a Pytorch Tensor

In [63]:
type(tsr)

torch.Tensor

Last but not the least, Python and numpy primer: https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb